server:
  port: 8081

spring:
  application:
    name: user-service
  #    database
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=test;encrypt=true;trustServerCertificate=true;
    username: sa
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format-sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'